name: Publish to GiyhubPages
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build-deployGHP:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@master
        with:
          persist-credentials: false
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install ğŸ”§
        run: yarn install
      - name: Build ğŸ—ï¸
        run: 
          yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          publish_dir: ./dist
      - name: Deploy GitHub Pages ğŸš€
    run: yarn deploy
    env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
